# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classifier.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 704)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 521, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtLable = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtLable.setObjectName("txtLable")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtLable)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtScoreContent = QtWidgets.QTextEdit(self.groupBox_2)
        self.txtScoreContent.setEnabled(True)
        self.txtScoreContent.setObjectName("txtScoreContent")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtScoreContent)
        self.txtSResult = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtSResult.setReadOnly(True)
        self.txtSResult.setObjectName("txtSResult")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtSResult)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.txtSentiment = QtWidgets.QLineEdit(self.groupBox)
        self.txtSentiment.setEnabled(True)
        self.txtSentiment.setObjectName("txtSentiment")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtSentiment)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtAuthor = QtWidgets.QLineEdit(self.groupBox)
        self.txtAuthor.setObjectName("txtAuthor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtAuthor)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtTweetId = QtWidgets.QLineEdit(self.groupBox)
        self.txtTweetId.setPlaceholderText("")
        self.txtTweetId.setObjectName("txtTweetId")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtTweetId)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtEmotionContent = QtWidgets.QTextEdit(self.groupBox)
        self.txtEmotionContent.setPlaceholderText("")
        self.txtEmotionContent.setObjectName("txtEmotionContent")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtEmotionContent)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtEResult = QtWidgets.QLineEdit(self.groupBox)
        self.txtEResult.setReadOnly(True)
        self.txtEResult.setObjectName("txtEResult")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtEResult)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAnalyse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnAnalyse.setObjectName("btnAnalyse")
        self.horizontalLayout.addWidget(self.btnAnalyse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 650, 531, 41))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Score"))
        self.label_5.setText(_translate("MainWindow", "label"))
        self.txtLable.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "content"))
        self.txtScoreContent.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">bromwell high is a cartoon comedy. ran at the same time as some other programs about school such as years in the teaching profession lead believe that bromwell satire is much closer reality than is the survive the insightful students can see right through pathetic the of the whole all remind of the schools i knew and i saw the episode in a student repeatedly tried burn the i immediately at a classic here of welcome bromwell i expect that many adults of age think that bromwell high is far a pity that</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "result"))
        self.groupBox.setTitle(_translate("MainWindow", "Emotion"))
        self.txtSentiment.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "author"))
        self.txtAuthor.setText(_translate("MainWindow", "shengzhao"))
        self.label.setText(_translate("MainWindow", "tweet id"))
        self.txtTweetId.setText(_translate("MainWindow", "1054840"))
        self.label_4.setText(_translate("MainWindow", "content"))
        self.txtEmotionContent.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">know listenin bad habit earlier started freakin part =[</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "result"))
        self.label_2.setText(_translate("MainWindow", "sentiment"))
        self.btnAnalyse.setText(_translate("MainWindow", "analyse"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Label/Sentiment/Author/Id is not necessary, but it must exist to fit the format. </p><p>So we set them as default.</p></body></html>"))

